
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';

const firebaseConfig = {"apiKey":"AIzaSyCArgeAW7ZIk04UsOz5HweBt67hvIjzjE4","authDomain":"studio-7472438982-5c6cc.firebaseapp.com","projectId":"studio-7472438982-5c6cc","storageBucket":"studio-7472438982-5c6cc.appspot.com","messagingSenderId":"202133235846","appId":"1:202133235846:web:f921aff62de1e49621c907"};

let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const auth = getAuth(app);
const db = getFirestore(app);

// To avoid connecting to the emulator multiple times, we check if the
// emulators are already running. This is a robust way to connect in dev.
try {
    // @ts-ignore
    if (!auth.emulatorConfig) {
        connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
    }
    // @ts-ignore
    if (!db.emulator) {
        connectFirestoreEmulator(db, '127.0.0.1', 8080);
    }
} catch (e) {
    // This can happen in certain environments, we can ignore it.
}


export { app, auth, db, firebaseConfig };
