
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

const firebaseConfig = {"apiKey":"AIzaSyCArgeAW7ZIk04UsOz5HweBt67hvIjzjE4","authDomain":"studio-7472438982-5c6cc.firebaseapp.com","projectId":"studio-7472438982-5c6cc","storageBucket":"studio-7472438982-5c6cc.appspot.com","messagingSenderId":"202133235846","appId":"1:202133235846:web:f921aff62de1e49621c907"};

export { firebaseConfig };
