
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator } from 'firebase/firestore';

const firebaseConfig = {"apiKey":"AIzaSyCArgeAW7ZIk04UsOz5HweBt67hvIjzjE4","authDomain":"studio-7472438982-5c6cc.firebaseapp.com","projectId":"studio-7472438982-5c6cc","storageBucket":"studio-7472438982-5c6cc.appspot.com","messagingSenderId":"202133235846","appId":"1:202133235846:web:f921aff62de1e49621c907"};

let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const auth = getAuth(app);
const db = getFirestore(app);

// Use a try/catch block to gracefully handle environments where emulators are not running.
try {
    // @ts-ignore - This is a safe way to check for an existing emulator connection.
    if (!auth.emulatorConfig) {
        connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true });
    }
    // @ts-ignore - This is a safe way to check for an existing emulator connection.
    if (!db.emulator) {
        connectFirestoreEmulator(db, '127.0.0.1', 8080);
    }
} catch (e) {
    // This can happen in some environments (like production) where emulators are not available.
    // We can safely ignore this error.
    console.warn("Could not connect to Firebase emulators. This is expected in production.", e);
}


export { app, auth, db, firebaseConfig };
